#!/bin/bash

echo "Killing nvidia-uvm processes"

while true; do
    output=$(fuser /dev/nvidia-uvm -k)
    echo $output
    if [ "$output" = "" ]; then
        break;
    fi
    sleep 0.2
done

echo "nvidia-uvm processes killed"

echo "Restarting ollama"

sudo systemctl daemon-reload && sudo systemctl restart ollama && sudo modprobe -rf nvidia-uvm
